### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by koyuawsmbrtn** [eugenelepekhin/LogicCircuit#11]
How about adding support for dark mode? Opening this app on Windows 11 burned my eyes.

**Comment by eugenelepekhin** [comment]
Good idea, thanks.

**Comment by eugenelepekhin** [comment]
In the new version there is darker background by default. One can set it to white in the options dialog.
This is not a dark mode, but should be good enough to same eyes. Making real dark mode is problematic for user selected colors in text blocks. There is not good algorithm to auto convert colors, so they are visible on both dark and light mode.
