### ISSUE TITLE
error in the RS latch

### ISSUE THREAD

**Issue by ProjectCF** [eugenelepekhin/LogicCircuit#14]
I'm writing a 16-bit CPU(why this software forces little-endian? it makes me have to use a TZ16 to process it)
register F jumps by 2 instead of 1
the bug is in the circuit "RS" in "D" in"D4" in "D16" in "REGS" in "CPU" in "Main"
at first
![image](https://github.com/eugenelepekhin/LogicCircuit/assets/66152214/b094ae61-ec21-4ec6-baab-383623067823)
then
![image](https://github.com/eugenelepekhin/LogicCircuit/assets/66152214/040c0e12-d2a6-4f8a-b23a-9e874734d655)
at last
![image](https://github.com/eugenelepekhin/LogicCircuit/assets/66152214/62341b41-bb49-4c60-b7b1-161a12d2cf87)
why?
there're just two nor gates

**Comment by ProjectCF** [comment]
[16.zip](https://github.com/eugenelepekhin/LogicCircuit/files/13464222/16.zip)

**Comment by eugenelepekhin** [comment]
Your RS flip-flop is not edge synchronized. So, any changes in the outside circuits will cause changes in it's state. With big circuits it is hard to figure out what is wrong. So, I suggest to first build and test edge triggered flip-flop, and then use it in your circuitry.
The software does not force any endian, you probably built it that way. I don't know what is TZ16.
For sample flip-flops you can use sample project from https://logiccircuit.org/ or search forums there.
This space is for bugs in software, not for issues with schematics.

**Comment by ProjectCF** [comment]
ok
TZ16 is reversing bits(debugger treats bit0 as LSB but my project treats bit0 as MSB)

**Comment by ProjectCF** [comment]
and how to build an edge synchronized edge triggered D flip-flop with clr?
![image](https://github.com/eugenelepekhin/LogicCircuit/assets/66152214/dfd73646-2fff-4898-9597-9ed753e04e8f)
RS is only used in this

**Comment by ProjectCF** [comment]
the actually bug is
current output=0
s is set to 1
current output=1
s is set to 0
1cycle later
current output=1
but there are no changes
![image](https://github.com/eugenelepekhin/LogicCircuit/assets/66152214/d5098304-c757-4bed-bf7d-7cbf6a01edc0)
![image](https://github.com/eugenelepekhin/LogicCircuit/assets/66152214/2e68f86b-326b-4769-90b6-35852bd9c8d1)
![image](https://github.com/eugenelepekhin/LogicCircuit/assets/66152214/8d357703-1070-41b7-a82f-361aff92de02)
![image](https://github.com/eugenelepekhin/LogicCircuit/assets/66152214/344d2bbf-1655-46df-a3d5-ab746b48bd08)

**Comment by eugenelepekhin** [comment]
It's a lot if information about it on the web. For example look here: https://lambdageeks.com/master-slave-flip-flop/
You can start with JK flip flop and then build D flip flop from JK.
About the bug - I am sure you are getting more changes in the input than you think. If you double click the probe, you will see entire history of changes.

**Comment by eugenelepekhin** [comment]
this is not a bug, but question.
