### ISSUE TITLE
Cable recognizes 1 bit less than the pin

### ISSUE THREAD

**Issue by luis-nav** [eugenelepekhin/LogicCircuit#6]
![image](https://user-images.githubusercontent.com/85853102/167716783-21c11652-78ce-4fba-973b-0e1faa6b83ba.png)
![image](https://user-images.githubusercontent.com/85853102/167716814-8855c37b-167f-4c0d-9dd6-4574bf62a3a1.png)

I have this circuit with an output of 29 bits, but when i connect the cable it only recognizes 28 bits

**Comment by eugenelepekhin** [comment]
It may be because some of the wires were optimized out. Such optimization can happen if one of the wires were not connected to any input.
If you want me to look deeper, please provide your circuit project file.

**Comment by eugenelepekhin** [comment]
If you have any more details on the case please reopen it again.
