### ISSUE TITLE
[Suggestion] Custom Frequency

### ISSUE THREAD

**Issue by ottozumkeller** [eugenelepekhin/LogicCircuit#8]
Hello, I have a suggestion:
It would be useful to be able to set a custom frequency, as I find that 1 to 50 is a bit limiting. Maybe you can add some kind of text field where I can enter my own frequency?

**Comment by eugenelepekhin** [comment]
Hello Otto,
You can click on the frequency slider and then use your keyboard to move it by 1 left or right or move it by 10 with page up / page down keys.
Can it solve your problem?

**Comment by ottozumkeller** [comment]
No, not exactly. I mean, even with the slider I can only set the frequency to a maximum of 50 Hz. As far as I have seen, however, it is not possible to set the frequency to, for example, 60 Hz. That's why I wrote this suggestion. If this is possible and I just haven't seen it, please correct me. If not, I would suggest a larger interval (greater than 1 - 50, maybe 1 - 1000, etc. ) for the slider or an input field.

**Comment by eugenelepekhin** [comment]
You can set frequency to maximum with checkbox below the slider. In this case the simulation will run as fast as possible.
Setting frequency to exact number higher than 50 is technically impossible as windows time slice will restrict this. Actually, it doesn't allow it above 32 or 35Hz.

**Comment by ottozumkeller** [comment]
ok, thank you very much for your answer. If it's not possible, I guess there's no other way.
